public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1, объявление переменных:");
        var dog=8.0;
        var cat=3.6;
        var paper=763789;
        System.out.println("dog = "+dog);
        System.out.println("cat = "+cat);
        System.out.println("paper = "+paper);
        System.out.println();
        System.out.println("Задача 2, прибавить по 4 к каждой переменной:");
        dog=dog+4;
        cat=cat+4;
        paper=paper+4;
        System.out.println("dog = "+dog);
        System.out.println("cat = "+cat);
        System.out.println("paper = "+paper);
        System.out.println();
        System.out.println("Задача 3, уменьшить каждую переменную:");
        dog=dog-3.5;
        cat=cat-1.6;
        paper=paper-7939;
        System.out.println("dog = "+dog);
        System.out.println("cat = "+cat);
        System.out.println("paper = "+paper);
        System.out.println();
        System.out.println("Задача 4, присвоение значений переменной friend:");
        var friend =19;
        System.out.println("Изначально значение переменной friend = "+friend);
        friend =friend*2;
        System.out.println("Увеличьте значение переменной на 2, friend = "+friend);
        friend =friend/7;
        System.out.println("поделите значение на 7, friend = "+friend);
        System.out.println();
        System.out.println("Задача 5, присвоение значений переменной  frog:");
        var  frog =3.5;
        System.out.println("Изначально значение переменной  frog = "+ frog);
        frog = frog*10;
        System.out.println("Увеличьте переменную в 10 раз,  frog = "+ frog);
        frog = frog/3.5;
        System.out.println("поделите значение на 3.5,  frog = "+ frog);
        frog = frog+4;
        System.out.println("Добавьте к последнему значению переменной 4,  frog = "+ frog);
        System.out.println();
        System.out.println("Задача 6, про массы боксеров:");
        var  theWeightOfTheBoxer1 =78.2;
        var  theWeightOfTheBoxer2 =82.7;
        var  theWeightOfBothBoxers =theWeightOfTheBoxer1+theWeightOfTheBoxer2;
        System.out.println("масса первого боксера = "+ theWeightOfTheBoxer1);
        System.out.println("масса второго боксера = "+ theWeightOfTheBoxer2);
        System.out.println("масса обоих боксеров = "+ theWeightOfBothBoxers);
        System.out.println();
        System.out.println("Задача 7, Найдите остаток от деления между двумя весами:");
        var  theRemainderOfTheDivision =theWeightOfTheBoxer2/theWeightOfTheBoxer1;
        System.out.println("Oстаток = "+ theRemainderOfTheDivision);
        System.out.println();
        System.out.println("Задача 8, про сотрудников и часы работы:");
        var  watch =640;
        var  oneEmployeesHours=8;
        var workers=watch/oneEmployeesHours;
        System.out.println("Если всего часов работы в компании — "+watch+",");
        System.out.println("а один работник может работать всего "+oneEmployeesHours+" часов,");
        System.out.println("то всего работников в компании — "+workers+" человек.");
        System.out.println();
        workers=workers+94;
        watch=oneEmployeesHours*workers;
        System.out.println("Если же работников в компании — "+workers+" человек,");
        System.out.println("а один работник по прежнему может работать всего лишь "+oneEmployeesHours+" часов,");
        System.out.println("то в компании должно быть "+watch+" часов поделено между сотрудниками.");

    }
}